# Generated by Django 5.0.6 on 2024-09-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='_is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
