# Generated by Django 5.0.6 on 2024-09-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_in_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
