# Generated by Django 5.0.6 on 2024-09-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_duration_in_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='info_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='info_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
