# Generated by Django 5.0.6 on 2024-08-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_usersubscription_plan_and_more'),
        ('subscriptions', '0005_alter_subscriptionplan_category'),
    ]

    operations = [
    ]
