# Generated by Django 5.0.6 on 2024-08-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_usersubscription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=10),
        ),
    ]
