# Generated by Django 5.0.6 on 2024-08-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('pick', models.CharField(max_length=255)),
                ('odd', models.FloatField()),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
    ]
