# Generated by Django 5.0.6 on 2024-08-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
